from odoo import api, fields, models, _
from cStringIO import StringIO
from datetime import datetime, timedelta
import xlsxwriter
import base64
import itertools
import operator
import time
import pytz


class LaporanPenjHarianWizard(models.TransientModel):
    _name = 'laporan.penj.harian.report.wizard'
    
    start_period = fields.Date(string='Start Period')
    end_period = fields.Date(string='End Period')
    state_x = fields.Selection((('choose', 'choose'), ('get', 'get')), default='choose')
    data_x = fields.Binary('File', readonly=True)
    name = fields.Char('Filename', readonly=True)
    check_all=fields.Boolean('Check')
    

    @api.multi
    def generate_excel(self):
#         form_bc_obj = self.env['sale.order']
        for this in self:
#             start_period = this.start_period
#             end_period = this.end_period
# #             timezone = pytz.timezone(self._context.get('tz') or 'UTC')
# #             utc_tz = pytz.utc.localize(today, '%d %b %Y %H:%M').astimezone(timezone)
#             sp=datetime.strptime(start_period, '%Y-%m-%d')
#             ep=datetime.strptime(end_period, '%Y-%m-%d')
            
            bz = StringIO()
            workbook = xlsxwriter.Workbook(bz)
            filename = str(self.name)+'.xlsx'
            worksheet1 = workbook.add_worksheet('LPH.report')
            worksheet2 = workbook.add_worksheet('LPH.report2')
            worksheet3 = workbook.add_worksheet('LPH.report3')
            merge_format = workbook.add_format({'bold':1, 'align': 'center'})
            merge_format.set_font_name('Arial')
            merge_format.set_font_size('10')
            ################################################################
            ukuran = workbook.add_format({'bold':1})
            ukuran.set_font_name('Arial')
            ukuran.set_font_size('10')
            #################################################################
            bold = workbook.add_format({'bold': True })
            #################################################################
            size = workbook.add_format()
            size.set_font_name('Arial')
            size.set_font_size('10')
            #########################################################################################
            normal_bold_border = workbook.add_format({'bold': 1,'valign':'vcenter','align':'center'})
            normal_bold_border.set_text_wrap()
            normal_bold_border.set_font_name('Arial')
            normal_bold_border.set_font_size('10')
            normal_bold_border.set_border()
            ################################################################
            format = workbook.add_format({'bold':1})
            format.set_font_color('blue')
            format.set_font_name('Arial')
            format.set_font_size('10')
            ################################################################
            worksheet1.merge_range('A1:B1', 'Laporan Penjualan Harian', ukuran)
            worksheet1.merge_range('A3:B3', '*)Daily Report', format)
            worksheet1.write('A4', 'Start Period:', ukuran)
            worksheet1.write('C4', 'End Period:', ukuran)
            worksheet1.write('E4', 'Print Date:', ukuran)
            worksheet1.merge_range('A6:A7', 'Branch', normal_bold_border)
            worksheet1.merge_range('B6:B7', 'Store Name', normal_bold_border)
            worksheet1.merge_range('C6:C7', 'No', normal_bold_border)
            worksheet1.merge_range('D6:D7', 'Product', normal_bold_border)
            worksheet1.merge_range('E6:E7', 'Price', normal_bold_border)
            worksheet1.merge_range('F6:F7', 'Qty', normal_bold_border)
            worksheet1.merge_range('G6:H6', 'Disc', normal_bold_border)
            worksheet1.write('G7', '%', normal_bold_border)
            worksheet1.write('H7', 'Rp', normal_bold_border)
            worksheet1.merge_range('I6:I7', 'Total', normal_bold_border)
            worksheet1.merge_range('B8:B11', 'customer', normal_bold_border)
            worksheet1.merge_range('B13:B16','', normal_bold_border)
            worksheet1.write('A20', 'Taxes (Rp)', ukuran)
            worksheet1.write('A21', 'PPN 10%', size)
            worksheet1.write('A22', 'Total Sales (Rp)', ukuran)
            ########################################################################################
            worksheet1.write('A8','', normal_bold_border)
            worksheet1.write('A9','', normal_bold_border)
            worksheet1.write('A10','', normal_bold_border)
            worksheet1.write('A11','', normal_bold_border)
            worksheet1.write('A12','', normal_bold_border)
            worksheet1.write('A13','', normal_bold_border)
            worksheet1.write('A14','', normal_bold_border)
            worksheet1.write('A15','', normal_bold_border)
            worksheet1.write('A16','', normal_bold_border)
            worksheet1.write('A17','', normal_bold_border)
            worksheet1.write('A18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('B12','', normal_bold_border)
            worksheet1.write('B17','', normal_bold_border)
            worksheet1.write('B18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('C8','', normal_bold_border)
            worksheet1.write('C9','', normal_bold_border)
            worksheet1.write('C10','', normal_bold_border)
            worksheet1.write('C11','', normal_bold_border)
            worksheet1.write('C12','', normal_bold_border)
            worksheet1.write('C13','', normal_bold_border)
            worksheet1.write('C14','', normal_bold_border)
            worksheet1.write('C15','', normal_bold_border)
            worksheet1.write('C16','', normal_bold_border)
            worksheet1.write('C17','', normal_bold_border)
            worksheet1.write('C18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('D8','', normal_bold_border)
            worksheet1.write('D9','', normal_bold_border)
            worksheet1.write('D10','', normal_bold_border)
            worksheet1.write('D11','', normal_bold_border)
            worksheet1.write('D12','', normal_bold_border)
            worksheet1.write('D13','', normal_bold_border)
            worksheet1.write('D14','', normal_bold_border)
            worksheet1.write('D15','', normal_bold_border)
            worksheet1.write('D16','', normal_bold_border)
            worksheet1.write('D17','', normal_bold_border)
            worksheet1.write('D18','', normal_bold_border)
            worksheet1.write('E8','', normal_bold_border)
            worksheet1.write('E9','', normal_bold_border)
            worksheet1.write('E10','', normal_bold_border)
            worksheet1.write('E11','', normal_bold_border)
            worksheet1.write('E12','', normal_bold_border)
            worksheet1.write('E13','', normal_bold_border)
            worksheet1.write('E14','', normal_bold_border)
            worksheet1.write('E15','', normal_bold_border)
            worksheet1.write('E16','', normal_bold_border)
            worksheet1.write('E17','', normal_bold_border)
            worksheet1.write('E18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('F8','', normal_bold_border)
            worksheet1.write('F9','', normal_bold_border)
            worksheet1.write('F10','', normal_bold_border)
            worksheet1.write('F11','', normal_bold_border)
            worksheet1.write('F12','', normal_bold_border)
            worksheet1.write('F13','', normal_bold_border)
            worksheet1.write('F14','', normal_bold_border)
            worksheet1.write('F15','', normal_bold_border)
            worksheet1.write('F16','', normal_bold_border)
            worksheet1.write('F17','', normal_bold_border)
            worksheet1.write('F18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('G8','', normal_bold_border)
            worksheet1.write('G9','', normal_bold_border)
            worksheet1.write('G10','', normal_bold_border)
            worksheet1.write('G11','', normal_bold_border)
            worksheet1.write('G12','', normal_bold_border)
            worksheet1.write('G13','', normal_bold_border)
            worksheet1.write('G14','', normal_bold_border)
            worksheet1.write('G15','', normal_bold_border)
            worksheet1.write('G16','', normal_bold_border)
            worksheet1.write('G17','', normal_bold_border)
            worksheet1.write('G18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('H8','', normal_bold_border)
            worksheet1.write('H9','', normal_bold_border)
            worksheet1.write('H10','', normal_bold_border)
            worksheet1.write('H11','', normal_bold_border)
            worksheet1.write('H12','', normal_bold_border)
            worksheet1.write('H13','', normal_bold_border)
            worksheet1.write('H14','', normal_bold_border)
            worksheet1.write('H15','', normal_bold_border)
            worksheet1.write('H16','', normal_bold_border)
            worksheet1.write('H17','', normal_bold_border)
            worksheet1.write('H18','', normal_bold_border)
            ########################################################################################
            worksheet1.write('I8','', normal_bold_border)
            worksheet1.write('I9','', normal_bold_border)
            worksheet1.write('I10','', normal_bold_border)
            worksheet1.write('I11','', normal_bold_border)
            worksheet1.write('I12','', normal_bold_border)
            worksheet1.write('I13','', normal_bold_border)
            worksheet1.write('I14','', normal_bold_border)
            worksheet1.write('I15','', normal_bold_border)
            worksheet1.write('I16','', normal_bold_border)
            worksheet1.write('I17','', normal_bold_border)
            worksheet1.write('I18','', normal_bold_border)
            ########################################################################################
             
              
            worksheet2.merge_range('A1:H1', 'REKAPITULASI PENJUALAN PRODUK', merge_format)
            worksheet2.merge_range('A3:B3', '*)Daily Report', format)
            worksheet2.merge_range('A4:B4', 'Store Name:', ukuran)
            worksheet2.write('B5', 'Start Period:', ukuran)
            worksheet2.write('C5', 'End Period:', ukuran)
            worksheet2.write('F5', 'Print Date:', ukuran)
            worksheet2.merge_range('A7:A8', 'No', normal_bold_border)
            worksheet2.merge_range('B7:B8', 'Product', normal_bold_border)
            worksheet2.merge_range('C7:C8', 'Price', normal_bold_border)
            worksheet2.merge_range('D7:D8', 'Qty', normal_bold_border)
            worksheet2.merge_range('E7:F7', 'Disc', normal_bold_border)
            worksheet2.write('E8', '%', normal_bold_border)
            worksheet2.write('F8', 'Rp', normal_bold_border)
            worksheet2.merge_range('G7:G8', 'Total', normal_bold_border)
            worksheet2.merge_range('H7:H8', 'Ppn', normal_bold_border)
            worksheet2.merge_range('E9:E11','', normal_bold_border)
            worksheet2.merge_range('A16:G16','', normal_bold_border)
            worksheet2.merge_range('A19:F19','Total Uang Disetor', normal_bold_border)
            worksheet2.write('A21:B21', 'Taxes (Rp)', ukuran)
            worksheet2.write('A22:B22', 'PPN 10%', size)
            worksheet2.write('A23:B23', 'Total Sales (Rp)', ukuran)
            worksheet2.write('A24:B24', 'Total Discount (Rp)', ukuran)
            worksheet2.write('A25:B25', 'Total Voucher (Rp)', ukuran)
            worksheet2.write('A26:B26', 'Total Uang Disetor (Rp)', ukuran)

            ########################################################################################
            worksheet2.write('A9','', normal_bold_border)
            worksheet2.write('A10','', normal_bold_border)
            worksheet2.write('A11','', normal_bold_border)
            worksheet2.write('A12','', normal_bold_border)
            worksheet2.write('A13','', normal_bold_border)
            worksheet2.write('A14','', normal_bold_border)
            worksheet2.write('A15','', normal_bold_border)
            worksheet2.merge_range('A16:G16','', normal_bold_border)
            worksheet2.merge_range('A17:A18','', normal_bold_border)
            ########################################################################################
            worksheet2.write('B9','', normal_bold_border)
            worksheet2.write('B10','', normal_bold_border)
            worksheet2.write('B11','', normal_bold_border)
            worksheet2.write('B12','', normal_bold_border)
            worksheet2.write('B13','', normal_bold_border)
            worksheet2.write('B14','', normal_bold_border)
            worksheet2.write('B15','', normal_bold_border)
            worksheet2.write('B17','', normal_bold_border)
            worksheet2.write('B18','', normal_bold_border)    
            ########################################################################################
            worksheet2.write('C9','', normal_bold_border)
            worksheet2.write('C10','', normal_bold_border)
            worksheet2.write('C11','', normal_bold_border)
            worksheet2.write('C12','', normal_bold_border)
            worksheet2.write('C13','', normal_bold_border)
            worksheet2.write('C14','', normal_bold_border)
            worksheet2.write('C15','', normal_bold_border)
            worksheet2.write('C17','', normal_bold_border)
            worksheet2.merge_range('C18:D18','', normal_bold_border)
            ########################################################################################
            worksheet2.write('D9','', normal_bold_border)
            worksheet2.write('D10','', normal_bold_border)
            worksheet2.write('D11','', normal_bold_border)
            worksheet2.write('D12','', normal_bold_border)
            worksheet2.write('D13','', normal_bold_border)
            worksheet2.write('D14','', normal_bold_border)
            worksheet2.write('D15','', normal_bold_border)
            worksheet2.write('D17','', normal_bold_border)
            ########################################################################################
            worksheet2.merge_range('E9:E11','', normal_bold_border)
            worksheet2.write('E12','', normal_bold_border)
            worksheet2.write('E13','', normal_bold_border)
            worksheet2.write('E14','', normal_bold_border)
            worksheet2.write('E15','', normal_bold_border)
            worksheet2.write('E17','', normal_bold_border)
            worksheet2.write('E18','', normal_bold_border)
            ########################################################################################
            worksheet2.write('F9','', normal_bold_border)
            worksheet2.write('F10','', normal_bold_border)
            worksheet2.write('F11','', normal_bold_border)
            worksheet2.write('F12','', normal_bold_border)
            worksheet2.write('F13','', normal_bold_border)
            worksheet2.write('F14','', normal_bold_border)
            worksheet2.write('F15','', normal_bold_border)
            worksheet2.write('F17','', normal_bold_border)
            worksheet2.write('F18','', normal_bold_border)
            ########################################################################################
            worksheet2.write('G9','', normal_bold_border)
            worksheet2.write('G10','', normal_bold_border)
            worksheet2.write('G11','', normal_bold_border)
            worksheet2.write('G12','', normal_bold_border)
            worksheet2.write('G13','', normal_bold_border)
            worksheet2.write('G14','', normal_bold_border)
            worksheet2.write('G15','', normal_bold_border)
            worksheet2.write('G17','', normal_bold_border)
            worksheet2.write('G18','', normal_bold_border)
            worksheet2.write('G19','', normal_bold_border)
            ########################################################################################
            worksheet2.write('H9','', normal_bold_border)
            worksheet2.write('H10','', normal_bold_border)
            worksheet2.write('H11','', normal_bold_border)
            worksheet2.write('H12','', normal_bold_border)
            worksheet2.write('H13','', normal_bold_border)
            worksheet2.write('H14','', normal_bold_border)
            worksheet2.write('H15','', normal_bold_border)
            worksheet2.write('H16','', normal_bold_border)
            worksheet2.write('H17','', normal_bold_border)
            worksheet2.write('H18','', normal_bold_border)
            worksheet2.write('H19','', normal_bold_border)
            ########################################################################################

            worksheet3.merge_range('A1:B1', 'Laporan Penjualan per Kategori', ukuran)
            worksheet3.write('B3', 'Start Period:', ukuran)
            worksheet3.write('D3', 'End Period:', ukuran)
            worksheet3.write('F3', 'Print Date:', ukuran)
            worksheet3.merge_range('A5:A6', 'No', normal_bold_border)
            worksheet3.merge_range('B5:B6', 'Product', normal_bold_border)
            worksheet3.merge_range('C5:C6', 'Price', normal_bold_border)
            worksheet3.merge_range('D5:D6', 'Kategori 1', normal_bold_border)
            worksheet3.merge_range('E5:F6', 'Kategori 2', normal_bold_border)
            worksheet3.merge_range('F5:F6', 'Kategori 3', normal_bold_border)
            worksheet3.merge_range('G5:G6', 'Kategori 4', normal_bold_border)
            worksheet3.merge_range('H5:H6', 'Kategori 5', normal_bold_border)
            worksheet3.merge_range('I5:I6', 'Qty', normal_bold_border)
            worksheet3.merge_range('J5:J6', 'Nominal Rp', normal_bold_border)
            worksheet3.merge_range('K5:K6', 'Disc', normal_bold_border)
            worksheet3.merge_range('L5:L6', 'Nominal Setelah Disc', normal_bold_border)

            ########################################################################################
            worksheet3.write('A7','', normal_bold_border)
            worksheet3.write('A8','', normal_bold_border)
            worksheet3.write('A9','', normal_bold_border)
            worksheet3.write('A10','', normal_bold_border)
            worksheet3.write('A11','', normal_bold_border)
            worksheet3.write('A12','', normal_bold_border)
            worksheet3.write('A13','', normal_bold_border)
            worksheet3.write('A14','', normal_bold_border)
            worksheet3.write('A15','', normal_bold_border)
            worksheet3.write('A16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('B7','', normal_bold_border)
            worksheet3.write('B8','', normal_bold_border)
            worksheet3.write('B9','', normal_bold_border)
            worksheet3.write('B10','', normal_bold_border)
            worksheet3.write('B11','', normal_bold_border)
            worksheet3.write('B12','', normal_bold_border)
            worksheet3.write('B13','', normal_bold_border)
            worksheet3.write('B14','', normal_bold_border)
            worksheet3.write('B15','', normal_bold_border)
            worksheet3.write('B16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('C7','', normal_bold_border)
            worksheet3.write('C8','', normal_bold_border)
            worksheet3.write('C9','', normal_bold_border)
            worksheet3.write('C10','', normal_bold_border)
            worksheet3.write('C11','', normal_bold_border)
            worksheet3.write('C12','', normal_bold_border)
            worksheet3.write('C13','', normal_bold_border)
            worksheet3.write('C14','', normal_bold_border)
            worksheet3.write('C15','', normal_bold_border)
            worksheet3.write('C16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('D7','', normal_bold_border)
            worksheet3.write('D8','', normal_bold_border)
            worksheet3.write('D9','', normal_bold_border)
            worksheet3.write('D10','', normal_bold_border)
            worksheet3.write('D11','', normal_bold_border)
            worksheet3.write('D12','', normal_bold_border)
            worksheet3.write('D13','', normal_bold_border)
            worksheet3.write('D14','', normal_bold_border)
            worksheet3.write('D15','', normal_bold_border)
            worksheet3.write('D16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('E7','', normal_bold_border)
            worksheet3.write('E8','', normal_bold_border)
            worksheet3.write('E9','', normal_bold_border)
            worksheet3.write('E10','', normal_bold_border)
            worksheet3.write('E11','', normal_bold_border)
            worksheet3.write('E12','', normal_bold_border)
            worksheet3.write('E13','', normal_bold_border)
            worksheet3.write('E14','', normal_bold_border)
            worksheet3.write('E15','', normal_bold_border)
            worksheet3.write('E16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('F7','', normal_bold_border)
            worksheet3.write('F8','', normal_bold_border)
            worksheet3.write('F9','', normal_bold_border)
            worksheet3.write('F10','', normal_bold_border)
            worksheet3.write('F11','', normal_bold_border)
            worksheet3.write('F12','', normal_bold_border)
            worksheet3.write('F13','', normal_bold_border)
            worksheet3.write('F14','', normal_bold_border)
            worksheet3.write('F15','', normal_bold_border)
            worksheet3.write('F16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('G7','', normal_bold_border)
            worksheet3.write('G8','', normal_bold_border)
            worksheet3.write('G9','', normal_bold_border)
            worksheet3.write('G10','', normal_bold_border)
            worksheet3.write('G11','', normal_bold_border)
            worksheet3.write('G12','', normal_bold_border)
            worksheet3.write('G13','', normal_bold_border)
            worksheet3.write('G14','', normal_bold_border)
            worksheet3.write('G15','', normal_bold_border)
            worksheet3.write('G16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('H7','', normal_bold_border)
            worksheet3.write('H8','', normal_bold_border)
            worksheet3.write('H9','', normal_bold_border)
            worksheet3.write('H10','', normal_bold_border)
            worksheet3.write('H11','', normal_bold_border)
            worksheet3.write('H12','', normal_bold_border)
            worksheet3.write('H13','', normal_bold_border)
            worksheet3.write('H14','', normal_bold_border)
            worksheet3.write('H15','', normal_bold_border)
            worksheet3.write('H16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('I7','', normal_bold_border)
            worksheet3.write('I8','', normal_bold_border)
            worksheet3.write('I9','', normal_bold_border)
            worksheet3.write('I10','', normal_bold_border)
            worksheet3.write('I11','', normal_bold_border)
            worksheet3.write('I12','', normal_bold_border)
            worksheet3.write('I13','', normal_bold_border)
            worksheet3.write('I14','', normal_bold_border)
            worksheet3.write('I15','', normal_bold_border)
            worksheet3.write('I16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('J7','', normal_bold_border)
            worksheet3.write('J8','', normal_bold_border)
            worksheet3.write('J9','', normal_bold_border)
            worksheet3.write('J10','', normal_bold_border)
            worksheet3.write('J11','', normal_bold_border)
            worksheet3.write('J12','', normal_bold_border)
            worksheet3.write('J13','', normal_bold_border)
            worksheet3.write('J14','', normal_bold_border)
            worksheet3.write('J15','', normal_bold_border)
            worksheet3.write('J16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('K7','', normal_bold_border)
            worksheet3.write('K8','', normal_bold_border)
            worksheet3.write('K9','', normal_bold_border)
            worksheet3.write('K10','', normal_bold_border)
            worksheet3.write('K11','', normal_bold_border)
            worksheet3.write('K12','', normal_bold_border)
            worksheet3.write('K13','', normal_bold_border)
            worksheet3.write('K14','', normal_bold_border)
            worksheet3.write('K15','', normal_bold_border)
            worksheet3.write('K16','', normal_bold_border)
            ########################################################################################
            worksheet3.write('L7','', normal_bold_border)
            worksheet3.write('L8','', normal_bold_border)
            worksheet3.write('L9','', normal_bold_border)
            worksheet3.write('L10','', normal_bold_border)
            worksheet3.write('L11','', normal_bold_border)
            worksheet3.write('L12','', normal_bold_border)
            worksheet3.write('L13','', normal_bold_border)
            worksheet3.write('L14','', normal_bold_border)
            worksheet3.write('L15','', normal_bold_border)
            worksheet3.write('L16','', normal_bold_border)
            ########################################################################################
           
            workbook.close()
                
            out = base64.encodestring(bz.getvalue())
            this.write({'state_x':'get', 'data_x':out, 'name': filename})
    
            ir_model_data = self.env['ir.model.data']
            bz.close()
            form_res = ir_model_data.get_object_reference('Magang_wizard', 'laporan_penj_harian_report_wizard_view')
            form_id = form_res and form_res[1] or False
            
                
            return {
                'name': ('Download XLS'),
                'view_type': 'form',
                'view_mode': 'form',
                'res_model': 'laporan.penj.harian.report.wizard',
                'res_id': this.id,
                'view_id': False,
                'views': [(form_id, 'form')],
                'type': 'ir.actions.act_window',
                'target': 'current'
            }